CREATE TABLE users (
  id VARCHAR(212) PRIMARY KEY NOT NULL,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id) VALUES ('abc123');

DROP TABLE users;